name: build and deploy backend application

on:
  push:
    paths:
    - 'seatr/server/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@main
    
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        CI='' npm run build --if-present 
      working-directory: ./seatr/server
      env:
        MAX_DISTANCE_API_KEY: ${{ secrets.MAX_DISTANCE_API_KEY }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        PORT: ${{ secrets.PORT }}
        SUBSCRIPTION_KEY: ${{ secrets.SUBSCRIPTION_KEY }}
         
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'seatr-the-best-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_SERVER_API }}
        package: ./seatr/server
