name: build and deploy front application

on:
  push:
    paths:
    - 'seatr/client/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@main
    
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    
    - name: npm install, build, and test
      run: |
        npm install
        CI='' npm run build
      working-directory: ./seatr/client
      env:
        REACT_APP_APIKEY: ${{ secrets.REACT_APP_APIKEY }}
        REACT_APP_AUTHDOMAIN: ${{ secrets.REACT_APP_AUTHDOMAIN }}
        REACT_APP_PID: ${{ secrets.REACT_APP_PID }}
        REACT_APP_SB: ${{ secrets.REACT_APP_SB }}
        REACT_APP_SID: ${{ secrets.REACT_APP_SID }}
        REACT_APP_APPID: ${{ secrets.REACT_APP_APPID }}
        REACT_APP_MID: ${{ secrets.REACT_APP_MID }}
        PORT: ${{ secrets.PORT }}
         
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'seatr-the-best-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./seatr/client